[package]
name = "pdslib"
version = "0.3.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pdslib"
crate-type = ["cdylib", "lib"]

[features]
default = []
experimental = [] # Experimental algorithms and APIs
fxhash = ["dep:rustc-hash"] # Use fxhash for HashMap and HashSet

[dependencies]
thiserror = "2.0"
anyhow = "1.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
rustc-hash = { version = "2.1.1", optional = true }

[dev-dependencies]
log4rs = "1.4"

[profile.release]
debug = true
