[project]
name = "evaluation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
