name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./pdslib
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./pdslib
      run: cargo test --verbose

  demo:
    runs-on: ubuntu-latest

    steps:
    - uses: extractions/setup-just@v2
    - name: Demo
      run: just demo
