name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --features experimental --verbose
    - name: Run integration tests
      run: |
        cargo test --package pdslib --features experimental --test ppa_demo -- --nocapture
        cargo test --package pdslib --features experimental --test simple_events_demo -- --nocapture
    - name: Run clippy
      run: cargo clippy --tests -- -D warnings
